#############################################################################
# Makefile for building: cwhois-0
# Generated by qmake (2.01a) (Qt 4.7.4) on: Thu Nov 3 22:56:25 2011
# Project:  ../cwhois-0.1/cwhois-0.1.pro
# Template: app
# Command: /home/mezgani/QtSDK/Desktop/Qt/474/gcc/bin/qmake -spec ../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/linux-g++-32 -o Makefile ../cwhois-0.1/cwhois-0.1.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m32 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m32 -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/linux-g++-32 -I../cwhois-0.1 -I../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/include/QtCore -I../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/include/QtGui -I../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/include -I../cwhois-0.1 -I../cwhois-0.1 -I. -I. -I.
LINK          = g++
LFLAGS        = -m32 -Wl,-O1 -Wl,-rpath,/home/mezgani/QtSDK/Desktop/Qt/474/gcc/lib
LIBS          = $(SUBLIBS)  -L/home/mezgani/QtSDK/Desktop/Qt/474/gcc/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/mezgani/QtSDK/Desktop/Qt/474/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../cwhois-0.1/client.cpp \
		../cwhois-0.1/main.cpp \
		../cwhois-0.1/sockets.cpp \
		../cwhois-0.1/whois.cpp moc_whois.cpp
OBJECTS       = client.o \
		main.o \
		sockets.o \
		whois.o \
		moc_whois.o
DIST          = ../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/g++.conf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/linux.conf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/release.prf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf \
		../cwhois-0.1/cwhois-0.1.pro
QMAKE_TARGET  = cwhois-0
DESTDIR       = 
TARGET        = cwhois-0

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_whois.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../cwhois-0.1/cwhois-0.1.pro  ../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/linux-g++-32/qmake.conf ../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/g++.conf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/linux.conf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/release.prf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf \
		../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec ../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/linux-g++-32 -o Makefile ../cwhois-0.1/cwhois-0.1.pro
../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/g++.conf:
../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/unix.conf:
../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/common/linux.conf:
../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/qconfig.pri:
../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/modules/qt_webkit_version.pri:
../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_functions.prf:
../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt_config.prf:
../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/exclusive_builds.prf:
../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_pre.prf:
../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/release.prf:
../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/default_post.prf:
../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/warn_on.prf:
../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/qt.prf:
../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/unix/thread.prf:
../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/moc.prf:
../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/resources.prf:
../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/uic.prf:
../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/yacc.prf:
../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/lex.prf:
../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec ../../../../mezgani/QtSDK/Desktop/Qt/474/gcc/mkspecs/linux-g++-32 -o Makefile ../cwhois-0.1/cwhois-0.1.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/cwhois-01.0.0 || $(MKDIR) .tmp/cwhois-01.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/cwhois-01.0.0/ && $(COPY_FILE) --parents ../cwhois-0.1/client.h ../cwhois-0.1/exception.h ../cwhois-0.1/sockets.h ../cwhois-0.1/whois.h .tmp/cwhois-01.0.0/ && $(COPY_FILE) --parents ../cwhois-0.1/client.cpp ../cwhois-0.1/main.cpp ../cwhois-0.1/sockets.cpp ../cwhois-0.1/whois.cpp .tmp/cwhois-01.0.0/ && $(COPY_FILE) --parents ../cwhois-0.1/whois.ui .tmp/cwhois-01.0.0/ && (cd `dirname .tmp/cwhois-01.0.0` && $(TAR) cwhois-01.0.0.tar cwhois-01.0.0 && $(COMPRESS) cwhois-01.0.0.tar) && $(MOVE) `dirname .tmp/cwhois-01.0.0`/cwhois-01.0.0.tar.gz . && $(DEL_FILE) -r .tmp/cwhois-01.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_whois.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_whois.cpp
moc_whois.cpp: ui_whois.h \
		../cwhois-0.1/client.h \
		../cwhois-0.1/sockets.h \
		../cwhois-0.1/whois.h
	/home/mezgani/QtSDK/Desktop/Qt/474/gcc/bin/moc $(DEFINES) $(INCPATH) ../cwhois-0.1/whois.h -o moc_whois.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_whois.h
compiler_uic_clean:
	-$(DEL_FILE) ui_whois.h
ui_whois.h: ../cwhois-0.1/whois.ui
	/home/mezgani/QtSDK/Desktop/Qt/474/gcc/bin/uic ../cwhois-0.1/whois.ui -o ui_whois.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

client.o: ../cwhois-0.1/client.cpp ../cwhois-0.1/client.h \
		../cwhois-0.1/sockets.h \
		../cwhois-0.1/exception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o client.o ../cwhois-0.1/client.cpp

main.o: ../cwhois-0.1/main.cpp ../cwhois-0.1/whois.h \
		ui_whois.h \
		../cwhois-0.1/client.h \
		../cwhois-0.1/sockets.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../cwhois-0.1/main.cpp

sockets.o: ../cwhois-0.1/sockets.cpp ../cwhois-0.1/sockets.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sockets.o ../cwhois-0.1/sockets.cpp

whois.o: ../cwhois-0.1/whois.cpp ../cwhois-0.1/sockets.h \
		../cwhois-0.1/whois.h \
		ui_whois.h \
		../cwhois-0.1/client.h \
		../cwhois-0.1/exception.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o whois.o ../cwhois-0.1/whois.cpp

moc_whois.o: moc_whois.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_whois.o moc_whois.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

